# Generated by Django 4.1.3 on 2022-11-02 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique_for_month=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concentrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Сырье')),
                ('iron', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Железо')),
                ('silicon', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Кремний')),
                ('aluminum', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Алюминий')),
                ('calcium', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Кальций')),
                ('sulfur', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Сера')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='concentrate.month')),
            ],
        ),
    ]
