# Generated by Django 4.1.3 on 2022-11-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentrate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
