# Generated by Django 4.1.3 on 2022-11-02 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concentrate', '0002_alter_month_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concentrate',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='concentrate.month', verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='month',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Месяц'),
        ),
    ]
