# Generated by Django 4.1.3 on 2022-11-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concentrate', '0003_alter_concentrate_month_alter_month_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concentrate',
            options={'verbose_name': 'Концентрат', 'verbose_name_plural': 'Концентрат'},
        ),
        migrations.AlterModelOptions(
            name='month',
            options={'verbose_name': 'Месяц', 'verbose_name_plural': 'Месяц'},
        ),
    ]
