# Generated by Django 4.1.3 on 2022-11-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentrate', '0004_alter_concentrate_options_alter_month_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concentrate',
            options={'ordering': ['id'], 'verbose_name': 'Концентрат', 'verbose_name_plural': 'Концентрат'},
        ),
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ['id'], 'verbose_name': 'Месяц', 'verbose_name_plural': 'Месяц'},
        ),
        migrations.AlterField(
            model_name='month',
            name='name',
            field=models.CharField(max_length=15, unique=True, verbose_name='Месяц'),
        ),
    ]
