# Generated by Django 4.1.3 on 2022-11-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentrate', '0005_alter_concentrate_options_alter_month_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='name',
        ),
        migrations.AddField(
            model_name='month',
            name='month',
            field=models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('DECEMBER', 'December')], default='JANUARY', max_length=9),
        ),
        migrations.AlterField(
            model_name='concentrate',
            name='aluminum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Содержание алюминия'),
        ),
        migrations.AlterField(
            model_name='concentrate',
            name='calcium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Содержание кальция'),
        ),
        migrations.AlterField(
            model_name='concentrate',
            name='iron',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Содержание железа'),
        ),
        migrations.AlterField(
            model_name='concentrate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование сырья'),
        ),
        migrations.AlterField(
            model_name='concentrate',
            name='silicon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Содержание кремния'),
        ),
        migrations.AlterField(
            model_name='concentrate',
            name='sulfur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Содержание серы'),
        ),
    ]
