# Generated by Django 4.1.3 on 2022-11-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentrate', '0008_alter_month_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concentrate',
            name='month',
            field=models.CharField(choices=[('Январь', 'Январь'), ('Февраль', 'Февраль'), ('Март', 'Март'), ('Апрель', 'Апрель'), ('Май', 'Май'), ('Июнь', 'Июнь'), ('Июль', 'Июль'), ('Август', 'Август'), ('Сентябрь', 'Сентябрь'), ('Октябрь', 'Октябрь'), ('Ноябрь', 'Ноябрь'), ('Декабрь', 'Декабрь')], default='Январь', max_length=8),
        ),
        migrations.DeleteModel(
            name='Month',
        ),
    ]
